---
title: "R Notebook"
output: html_notebook
---

Loading the data in first...

```{r}
suppressMessages(library(tidyverse))
suppressMessages(library(Lahman))

Batting <- as_tibble(Batting)

year_batting_summary <- Batting %>% 
  filter(lgID %in% c("AL", "NL")) %>% 
  group_by(yearID) %>%
  summarize_at(vars (H, HR, SO, BB, AB),
               sum, na.rm = TRUE) %>% 
  mutate(batting_avg = H / AB)

```


It appears that the data is loaded, let's check

```{r}

year_batting_summary

```




```{r}

year_batting_summary %>% 
  ggplot() + 
  geom_point(aes(x = yearID, y = HR))

## this implicitely uses coord_cartesian, and also implicitely sets the x y axis to continuous

year_batting_summary %>% 
  ggplot() + 
  geom_point(aes(x = yearID, y = HR)) +
  geom_line(aes(x = yearID, y = HR))

## or we could just do this if multiple geometric objects share the same aesthetics

year_batting_summary %>% 
  ggplot(aes(x = yearID, y = HR)) + 
  geom_point() +
  geom_line() +
  scale_x_continuous() +
  scale_y_continuous()


```

## Custom Scale limits 

We can also set custom limits if we input a vector.

```{r}

year_batting_summary %>% 
  ggplot(aes(x = yearID, y = HR)) + 
  geom_point() +
  geom_line() +
  scale_x_continuous(limits = c(2000, 2018))

```

We can also explicitely set the axis and the label locations

```{r}

year_batting_summary %>% 
  ggplot(aes(x = yearID, y = HR)) + 
  geom_point() +
  geom_line() +
  scale_y_continuous(breaks = seq(0, 6000, by = 1000))

```


We can also reverse the scale and stuff


```{r}

year_batting_summary %>% 
  ggplot(aes(x = yearID, y = HR)) + 
  geom_point() +
  geom_line() +
scale_y_continuous(breaks = seq(0, 6000, by = 1000))

```


## Add a statistical summary


```{r}

year_batting_summary %>% 
  ggplot(aes(x = yearID, y = HR)) + 
  geom_point() +
  geom_line() +
  stat_smooth()
  
  
```




