---
title: "EDA-pt1"
author: "me"
date: "6/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading in the data:
```{r}
# To download the data
# if you would prefer devtools installation
if (!requireNamespace('devtools', quietly = TRUE)){
  install.packages('devtools')
}
# Alternatively, using the devtools package:
devtools::install_github(repo = "saiemgilani/wehoop")




```



```{r}

library(wehoop)
library(tidyverse)
wnba_pbp_data <- load_wnba_pbp(2021)

wnba_pbp_data

# Get the shots and clean this data a bit:
wnba_shots_data <- wnba_pbp_data %>%
  filter(shooting_play)
# Remove unnecessary columns:
wnba_shots_data <- wnba_shots_data %>%
  dplyr::select(-shooting_play, -id, -participants_2_athlete_id,
                -type_abbreviation, -season, -season_type, 
                -home_team_spread, -game_spread, -home_favorite)


wnba_shots_data

```

## Filtering the data

```{r}
wsd <-wnba_shots_data

list_of_games <- unique(wsd$game_id)

## grabbing data from a single game
single_game <- wsd %>% 
  filter(game_id == "401320565")

single_game

```

## Todo List ----

1. Try to graph the x, y, and color base on success
2. Number of Successes per Quarter
3. 

four 10 minute quarters 
2 quarters per halves


```{r}

sg <- single_game %>% 
  mutate(distance = sqrt((coordinate_x-25)^2 + coordinate_y^2)) %>% 
  filter(coordinate_x > 0 & coordinate_y > 0)


sg %>% 
  ggplot() + 
  geom_point(aes(x = coordinate_x, y = coordinate_y, color = distance))


```

```{r}

sg <- sg %>% 
  mutate(sequence_number = as.integer(sequence_number))

sg_q1 <- sg %>% 
  filter(period_display_value == "1st Quarter")


sg %>% 
  ggplot() + 
  geom_point(aes(x = sequence_number, y = distance, shape = team_id, color = period_display_value)) +
  labs(title = "Development of distance through the 4 quarters")


```

## Test ----

```{r}

library(lubridate)

sg
sg <- sg %>% 
  arrange(sequence_number)


sg %>% 
  ggplot() + 
  geom_point(aes(x = sequence_number, y = distance, size = scoring_play, shape = team_id, color = period_display_value)) +
  labs(title = "Development of distance and success through the 4 quarters",
       x = "Sequence of shots", y = "distance from hoop")


```


## Lets check it for each quarter

First find the team that "won" and by how much 


```{r}

final_score_home <- sg$home_score[length(sg$home_score)]
print(final_score_home)
final_score_away <- sg$away_score[length(sg$away_score)]
print(final_score_away)

away_id <- sg$away_team_id[1]
home_id <- sg$home_team_id[1]

if ( final_score_home > final_score_away) {
  winning_id = sg$home_team_id[1]
  losing_id = sg$away_team_id[1]
} else {
  winning_id = sg$away_team_id[1]
  losing_id = sg$home_team_id[1]
}


sg <- sg %>% 
  mutate(win_id = case_when(team_id == winning_id ~ "win_team",
                              team_id == losing_id ~ "lost_team"))


sg %>% 
  ggplot() + 
  geom_point(aes(x = sequence_number, y = distance, size = scoring_play, shape = win_id, color = period_display_value)) +
  labs(title = "Development of distance and success through the 4 quarters",
       x = "Sequence of shots", y = "distance from hoop")

```


Graphing the score alongisde this:

```{r}


library(reshape2)

sscores <- sg %>% 
  select(away_score, home_score, sequence_number)
         
sscores

sg

sg %>% 
  ggplot() +
  geom_point(aes(x = sequence_number, y = home_score))


#melt data frame into long format
sscores <-melt(sscores ,  id.vars = 'sequence_number', variable.name = 'series')

library(lubridate)
# a <- ms("10:00") - ms("1:05") # "9M -5S"
# b <- ms("	9 : 37")
# a
# a <- ms("5600") 
# a
# (a * 4) + b

minute(a) # gives 9 

tenmin - b

sscores %>% 
  ggplot() +
  geom_point(aes(x = sequence_number, y = value, color = series))

sgt <- sg %>% 
  select(clock_minutes, clock_seconds, period_number, away_score, home_score) %>% 
  mutate(seconds_elapsed_game = 600 - (as.integer(clock_minutes) * 60 + as.integer(clock_seconds))) %>% 
  mutate(seconds_with_period = (period_number - 1) * 10 * 60 + seconds_elapsed_game) %>% 
  mutate(lubed_time = seconds_to_period(seconds_with_period))

sscores <- sgt %>% 
  select(away_score, home_score, lubed_time) 

# pivot_longer(sscores, !lubed_time ,names_to = "lubed_time", values_to = "val")

# melt(sscores ,  id.vars = 'lubed_time', variable.name = 'series')

sscores %>% 
  ggplot() +
  geom_point(aes(x = lubed_time, y = away_score , color = "darkorange")) + 
  geom_point(aes(x = lubed_time, y = home_score , color = "darkblue")) + 
  scale_x_time()



melt(sscores, "lubed_time")

sscores %>% 
  ggplot() +
  geom_point(aes(x = lubed_time, y = value, color = series)) + scale_x_time()


# ms(sscores$lubed_time)


# (sscores$lubed_time)
```


## Change the data to time series dat


```{r}

library(lubridate)
td <- seconds_to_period(1532)

td


# Libraries
library(ggplot2)
library(dplyr)

# Dummy data
data <- data.frame(
  day = as.Date("2017-06-14") - 0:364,
  value = runif(365) + seq(-140, 224)^2 / 10000
)

data

# Most basic bubble plot
p <- ggplot(data, aes(x=day, y=value)) +
  geom_line() + 
  xlab("")
p

```









