---
title: "EDA-pt2-sum"
author: "me"
date: "6/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



### Loading The Libraries and Preparing the data

```{r}

library(wehoop)
library(tidyverse)
library(lubridate)

## Preparing the data ----------------


wnba_pbp_data <- load_wnba_pbp(2021)

# Get the shots and clean this data a bit:
wnba_shots_data <- wnba_pbp_data %>%
  filter(shooting_play)
# Remove unnecessary columns:
wnba_shots_data <- wnba_shots_data %>%
  dplyr::select(-shooting_play, -id, -participants_2_athlete_id,
                -type_abbreviation, -season, -season_type, 
                -home_team_spread, -game_spread, -home_favorite)

write.csv(wnba_shots_data,'WNBA_shot_data.csv')
## Loading the data for a single game ----------------

wsd <-wnba_shots_data

list_of_SEA_won_games <- c(401320570, 401320578, 401320583, 401320590, 401320595, 401320605, 401320610, 401320617) # removed: none
list_of_games <- unique(wsd$game_id)

##### looping through the 8 games and added them up together

# initializing empty dataframe
sea_wgames = data.frame()

for (curr_game in list_of_SEA_won_games) {
  print(paste("=> curr game: ", curr_game))


single_game <- wsd %>% 
  filter(game_id == curr_game)
#game 1: 401320570 401320578 401320583 401320590 401320595 401320605 401320610 401320617

sea_games <- wsd %>% 
  filter()

## Loading the data for a single game ----------------

sg <- single_game %>% 
  mutate(distance = sqrt((coordinate_x-25)^2 + coordinate_y^2)) %>% 
  filter(coordinate_x > 0 & coordinate_y > 0) %>% 
  mutate(sequence_number = as.integer(sequence_number))


## Add the time (min:sec) column to the game data ----------------

sg <- sg %>% 
  # select(clock_minutes, clock_seconds, period_number, away_score, home_score) %>% 
  mutate(seconds_elapsed_game = 600 - (as.integer(clock_minutes) * 60 + as.integer(clock_seconds))) %>% 
  mutate(seconds_with_period = (period_number - 1) * 10 * 60 + seconds_elapsed_game) %>% 
  mutate(time_corrected = seconds_to_period(seconds_with_period))



## Adding the winning team identifier column ----------------

final_score_home <- sg$home_score[length(sg$home_score)]
# print(final_score_home)
final_score_away <- sg$away_score[length(sg$away_score)]
# print(final_score_away)

away_id <- sg$away_team_id[1]
home_id <- sg$home_team_id[1]

away_abbrv <- sg$away_team_abbrev[1]
home_abbrv <- sg$home_team_abbrev[1]

if ( final_score_home > final_score_away) {
  winning_id = sg$home_team_id[1]
  losing_id = sg$away_team_id[1]
  win_abbrv = home_abbrv
  lose_abbrv = away_abbrv
} else {
  winning_id = sg$away_team_id[1]
  losing_id = sg$home_team_id[1]
  win_abbrv = away_abbrv
  lose_abbrv = home_abbrv
}

sg <- sg %>% 
  mutate(wl_abbrv = case_when(team_id == winning_id ~ paste(win_abbrv, "(W)"),
                              team_id == losing_id ~ paste(lose_abbrv, "(L)")),
         game_title = paste(paste(win_abbrv, "(W) vs",paste(lose_abbrv, "(L)"))))

print(paste(paste(win_abbrv, "(W) vs",paste(lose_abbrv, "(L)"))))

sea_wgames = rbind(sea_wgames, sg)
}


sea_wgames %>% 
  mutate(coordinate_x = coordinate_x - 25)


sea_wgames <- sea_wgames %>% 
  mutate(theta = acos(coordinate_x / distance) * (180 / pi))



## sanity check that the final dataset is what we wanted
unique(sea_wgames$game_id)

## Final Cleanups ----------------------

## This is the final dataset that has:
### 1. a win_team_id column that just says whether they are the winning or losing team
### 2. a time_corrected column in lubridate that allows for time series graphing. Make sure to include + scale_x_time() in graphing!

# df <- sg %>% 
#   select(-c( 'sequence_number', 'period_display_value', "participants_0_athlete_id", "participants_1_athlete_id", "away_team_mascot",
#              "away_team_name_alt", "home_team_name_alt", "away_team_name", "home_team_mascot", "home_team_name", "lag_half", "lead_half",
#              "seconds_elapsed_game", "seconds_with_period", "clock_minutes", "clock_seconds", "half", "game_play_number"))

```



# Graphing the time series data base

```{r}



sg %>% 
  ggplot() +
  geom_vline(xintercept = 600, linetype="dotted", color = "blue", size=1.5) + 
  geom_vline(xintercept = 600*2, linetype="dotted", color = "blue", size=1.5) + 
  geom_vline(xintercept = 600*3, linetype="dotted", color = "blue", size=1.5) + 
  geom_point(aes(x = time_corrected, y = away_score , color = "away")) + 
  geom_point(aes(x = time_corrected, y = home_score , color = "home")) + 
  scale_x_time() +
  labs(title = "Score Over time") + 
  theme_bw()


sg %>% 
  filter(distance <= 30) %>% 
  ggplot() + 
  geom_vline(xintercept = 600, , color = "blue", size=1.5, alpha = 0.3) + 
  geom_vline(xintercept = 600*2, , color = "blue", size=1.5, alpha = 0.3)+ 
  geom_vline(xintercept = 600*3, , color = "blue", size=1.5, alpha = 0.3) + 
  geom_point(aes(x = time_corrected, y = distance, shape = wl_abbrv, size = scoring_play, color = wl_abbrv)) +
  scale_x_time() +
  labs(title = "Development of distance through the 4 quarters for 1 game", y = "Distance From Hoop", x = "Time") + 
  theme_bw()


# total_games <- c(401320570, 401320578, 401320583, 401320590, 401320595, 401320605, 401320610, 401320617)
games_of_interest <-  c(401320583)

sea_wgames %>% 
  filter(game_id %in% games_of_interest & period_number < 5) %>% 
  ggplot() + 
  geom_vline(xintercept = 600, , color = "blue", size=1.5, alpha = 0.3) + 
  geom_vline(xintercept = 600*2, , color = "blue", size=1.5, alpha = 0.3)+ 
  geom_vline(xintercept = 600*3, , color = "blue", size=1.5, alpha = 0.3) + 
  geom_point(aes(x = time_corrected, y = distance, shape = wl_abbrv, size = scoring_play, color = wl_abbrv)) +
  scale_shape_manual(values=c(16, 17, 19)) +
  scale_x_time() +
  # facet_wrap(~ game_title, ncol = 2) +
  labs(title = "Development of distance through the 4 quarters for 1 game", y = "Distance From Hoop", x = "Time") + 
  theme_bw()



sea_wgames %>% 
  filter(game_id %in% games_of_interest & period_number < 5) %>% 
  ggplot() + 
  geom_vline(xintercept = 600, , color = "blue", size=1.5, alpha = 0.3) + 
  geom_vline(xintercept = 600*2, , color = "blue", size=1.5, alpha = 0.3)+ 
  geom_vline(xintercept = 600*3, , color = "blue", size=1.5, alpha = 0.3) + 
  geom_point(aes(x = time_corrected, y = theta, shape = wl_abbrv, size = scoring_play, color = wl_abbrv)) +
  scale_shape_manual(values=c(16, 17, 19)) +
  scale_x_time() +
  # facet_wrap(~ game_title, ncol = 2) +
  labs(title = "Development of theta through the 4 quarters for 1 game", y = "Distance From Hoop", x = "Time") + 
  theme_bw()


```


``` {r}

### grabbing and graphing the delta distance trajectories so that I can cluster them

total_games <- c(401320570, 401320578, 401320583, 401320590, 401320595, 401320605, 401320610, 401320617)
games_of_interest <-  c(401320570)

distance_df <- data.frame()
sea_df <- data.frame()


for ( curr_game_id in total_games){
  print(curr_game_id)
  
  curr_game <- sea_wgames %>% 
    filter(game_id == curr_game_id)
  
  sea_traj = c()
  delta_distance_per_window = c()

  for ( i in seq(1,40)){
    
    start_sec <- 60 * (i - 1)
    end_sec <-  60 * (i)
    
    temp <- curr_game %>%
      filter(time_corrected > start_sec & time_corrected < end_sec) 
    
    win_distance_hit = sum(filter(temp, (wl_abbrv == "SEA (W)") & scoring_play == TRUE)$distance)
    win_distance_miss = sum(filter(temp, (wl_abbrv == "SEA (W)") & scoring_play == FALSE)$distance)
    
    other_distance_hit = sum(filter(temp, (wl_abbrv != "SEA (W)") & scoring_play == TRUE)$distance)
    other_distance_miss = sum(filter(temp, (wl_abbrv != "SEA (W)") & scoring_play == FALSE)$distance)
    
    if(is.na(win_distance_hit)){win_distance <-  0}
    if(is.na(win_distance_miss)){other_distance <- 0}
    if(is.na(other_distance_hit)){win_distance <-  0}
    if(is.na(other_distance_miss)){other_distance <- 0}
    
    win_distance = win_distance_hit * 1 + win_distance_miss
    other_distance = other_distance_hit * 1 + other_distance_miss
    
    dist_delta <- win_distance - other_distance
    
    delta_distance_per_window[i] = dist_delta
    
    ## just grabbing the seattle distance evolution 
    sea_traj[i] = sum(filter(temp, (wl_abbrv == "SEA (W)"))$distance) ## alternate between mean and sum
    
  }
  min_df = data.frame(minute = seq(1,40), delta_distance_per_window, game_id = as.factor(curr_game_id))
  sea_min_df = data.frame(minute = seq(1,40), sea_traj, game_id = as.factor(curr_game_id))
  
  distance_df <- rbind(distance_df , min_df)
  sea_df <- rbind(sea_df , sea_min_df)
  
  
}

distance_df


distance_df %>% 
  ggplot(aes(x = minute, y = delta_distance_per_window, color = game_id)) +
  geom_line() + 
  geom_point() + 
  labs(title = "The Delta Distance Trajectories for 8 games binned per each minute")
  

sea_df %>% 
  ggplot(aes(x = minute, y = sea_traj, color = game_id)) +
  geom_line() + 
  geom_point() + 
  labs(title = "The SEA Distance Trajectories for 8 games binned per each minute")

```


```{r}

distance_df %>% 
  ggplot(aes(x = minute, y = delta_distance_per_window, color = game_id)) +
  geom_line() + 
  geom_point() + 
  labs(title = "The Delta Distance Trajectories for 8 games binned per each minute")

```




## DTW 

```{r}

## I can swap out a different clustering method later

# library(dtw)
# 
# dist_df <- pivot_wider(distance_df, names_from = game_id, values_from = delta_distance_per_window) %>% 
#   dplyr::select(!minute)
# rownames(dist_df) <- seq(1,40)
# dist_df

library(kml)


dist_df <- pivot_wider(distance_df, names_from = minute, values_from = delta_distance_per_window)
dist_df <- pivot_wider(sea_df, names_from = minute, values_from = sea_traj)



dist_df <- as.data.frame(dist_df)
mycldf <- kml::cld(dist_df, timeInData = 2:41)

kml::kml(mycldf, nbRedrawing = 10)

kml::choice(mycldf)

dist_df$clust <- getClusters(mycldf, 3)

a <- dplyr::select(dist_df, game_id, clust)

ndistance_df <- merge(distance_df, a, by = "game_id", all.x = TRUE)


ndistance_df %>% 
  # filter(clust == "B") %>% 
  ggplot(aes(x = minute, y = delta_distance_per_window, color = game_id)) +
  geom_line() + 
  geom_point() + 
  facet_wrap(~clust, ncol = 1) +
  labs(title = "The Delta Distance Trajectories for 8 games clustered using KML")

sea_alone_cluster <- a

merge(sea_alone_cluster, a, by ="game_id", all.x = TRUE)

# dist(distance_df, method = "DTW")
# 
# sc <- read.table("synthetic_control.data.txt", header = F, sep = "")
# n <-10
# s <-sample(1:100, n)
# idx <- c(s, 100+s, 200+s, 300+s, 400+s, 500+s)
# sample2 <- sc[idx,]
# 
# n <-  40
# observedLabels <- c(rep(1,n), rep(2,n), rep(3,n), rep(4,n), rep(5,n), rep(6,n), rep(7,n), rep(8,n))
# 
# distMatrix <- dist(dist_df, method="DTW")
# 
# hc <- hclust(distMatrix, method="average")
# plot(hc, main="")

```

## histogramming based on the clusters

```{r}

clust_game_id <-filter(a, clust == "A")$game_id

c_sea_games <- merge(sea_wgames, a, by="game_id", all.x = TRUE)

c_sea_games %>% 
  filter(period_number < 5 & clust %in% c("A", "B", "C") & wl_abbrv == "SEA (W)") %>% 
  ggplot(aes(x = distance, color = clust)) +
  geom_freqpoly(aes(y = after_stat(density))) +
  facet_wrap(~ period_display_value, ncol = 2) +
  labs(title = "histogram of 3 clusters per quarter basis")



### histogramed each quarter based on each game
c_sea_games %>% 
  filter(period_number < 5 & wl_abbrv == "SEA (W)") %>% 
  ggplot(aes(x = distance, color = game_title)) +
  geom_freqpoly(aes(y = after_stat(density))) +
  facet_wrap(~ period_display_value, ncol = 2) +
  labs(title = "histogram of 3 clusters per quarter basis")

c_sea_games %>% 
  filter(distance > 40)

```

```{r}
g1 <- c_sea_games %>% 
  filter(period_number < 5 & wl_abbrv == "SEA (W)") %>% 
  ggplot(aes(x = coordinate_x)) +
  geom_freqpoly(aes(y = after_stat(density))) +
  facet_wrap(~ period_display_value, ncol = 2) +
  labs(title = "histogram of X coordinate for shots")


g2 <- c_sea_games %>% 
  filter(period_number < 5 & wl_abbrv == "SEA (W)") %>% 
  ggplot(aes(x = coordinate_y)) +
  geom_freqpoly(aes(y = after_stat(density))) +
  facet_wrap(~ period_display_value, ncol = 2) +
  labs(title = "histogram of Y coordinate for shots")


c_sea_games %>% 
  filter(period_number < 5 & wl_abbrv == "SEA (W)") %>% 
  ggplot(aes(x = distance)) +
  geom_histogram(aes(y = after_stat(density))) +
  facet_wrap(~period_display_value, ncol = 2) +
  labs(title = "distance for SEA over the 8 games they won")

library(patchwork)

g1 + g2

sea_wgames <- sea_wgames %>% 
  mutate(coordinate_x = (coordinate_x -25))

sea_wgames %>% 
  filter(wl_abbrv == "SEA (W)" & period_number < 5) %>% 
  ggplot() + 
  geom_hex(binwidth = c(2,2), aes(x = coordinate_x, y = coordinate_y)) + 
  scale_fill_gradient(low = "darkblue", high = "darkorange") +
  facet_wrap(~ period_display_value)
  # geom_density2d(aes(x = coordinate_x, y = coordinate_y))


sea_wgames <- sea_wgames %>% 
  mutate(theta = acos(coordinate_x / distance) * (180 / pi))


####### histograms of the change in shooting angle

sea_wgames %>% 
  filter(wl_abbrv == "SEA (W)") %>% 
  ggplot() +
  geom_histogram(aes(x = theta), binwidth = 5) +
  # geom_density(aes(x = theta)) + 
  facet_wrap(~ period_display_value, ncol = 3) +
  scale_x_continuous(breaks = seq(0, 180, by = 30)) +
  labs(title = "Histograms of the Shooting Angle over the 4 quarters")
  # coord_polar(start = 0, direction=1)

sea_wgames %>% 
  filter(wl_abbrv == "SEA (W)") %>% 
  ggplot() +
  geom_freqpoly(aes(x = theta, color = game_title), binwidth = 5) +
  # geom_density(aes(x = theta)) + 
  facet_wrap(~ period_display_value, ncol = 3) +
  scale_x_continuous(breaks = seq(0, 180, by = 30)) +
  labs(title = "Histograms of the Shooting Angle over the 4 quarters")






```




## investigating SEA(W) vs MIN(L) : GAMEID 401320578

```{r}

sg <- sea_wgames %>% 
  filter(game_id == "401320578")
  

sg %>% 
  ggplot() +
  geom_freqpoly(aes(x = theta, color = wl_abbrv, linetype = scoring_play), binwidth = 5) +
  scale_linetype_manual(values=c("dashed", "solid"))+
  # scale_alpha_discrete(range = c(0.4, 1)) +
  # geom_density(aes(x = theta)) + 
  facet_wrap(~ period_display_value, ncol = 2) +
  # scale_x_continuous(breaks = seq(0, 180, by = 30)) +
  scale_x_reverse(breaks = seq(180, 0, by = -30)) +
  labs(title = "SEA (W) vs MIN (L) THETA plot")


sg %>% 
  ggplot() +
  geom_freqpoly(aes(x = distance, color = wl_abbrv, linetype = scoring_play), binwidth = 5) +
  scale_linetype_manual(values=c("dashed", "solid"))+
  facet_wrap(~ period_display_value, ncol = 2) +
  labs(title = "SEA (W) vs MIN (L) Distance plot")



sg  %>% 
  filter(period_number == 1) %>%
  ggplot() + 
  geom_point(aes(x = theta, y = time_corrected, shape = wl_abbrv, size = scoring_play, color = wl_abbrv)) +
  scale_shape_manual(values=c(16, 17, 19)) +
  scale_y_time() +
  scale_x_reverse(breaks = seq(180, 0, by = -30)) +
  labs(title = "Development of the angle through quarter 1",  y = "Time", x = "Theta") + 
  theme_bw()


sg %>% 
  ggplot() +
  geom_vline(xintercept = 600, linetype="dotted", color = "blue", size=1.5) + 
  geom_vline(xintercept = 600*2, linetype="dotted", color = "blue", size=1.5) + 
  geom_vline(xintercept = 600*3, linetype="dotted", color = "blue", size=1.5) + 
  geom_point(aes(x = time_corrected, y = home_score , color = "MIN (L)")) + 
  geom_point(aes(x = time_corrected, y = away_score , color = "SEA (W)")) + 
  # scale_color_manual(c("red", "blue")) +
  scale_x_time() +
  labs(title = "Score Over time") + 
  theme_bw()




sg %>% 
  filter(distance <= 30) %>% 
  ggplot() + 
  geom_vline(xintercept = 600, , color = "blue", size=1.5, alpha = 0.3) + 
  geom_vline(xintercept = 600*2, , color = "blue", size=1.5, alpha = 0.3)+ 
  geom_vline(xintercept = 600*3, , color = "blue", size=1.5, alpha = 0.3) + 
  geom_point(aes(x = time_corrected, y = distance, shape = scoring_play, size = 0.5, color = wl_abbrv)) +
  scale_shape_manual(values=c(4, 19)) +
  scale_x_time() +
  labs(title = "Development of distance through the 4 quarters for 1 game", y = "Distance From Hoop", x = "Time") + 
  theme_bw()


sg  %>%
  ggplot() +
  geom_hline(yintercept = 600, , color = "blue", size=1.5, alpha = 0.3) +
  geom_hline(yintercept = 600*2, , color = "blue", size=1.5, alpha = 0.3)+
  geom_hline(yintercept = 600*3, , color = "blue", size=1.5, alpha = 0.3) +
  geom_point(aes(x = theta, y = time_corrected, shape = scoring_play, size = 0.5, color = wl_abbrv)) +
  scale_shape_manual(values=c(4, 19)) +
  scale_y_time() +
  scale_x_reverse(breaks = seq(180, 0, by = -30)) +
  facet_wrap(~ game_title, ncol = 2) +
  labs(title = "Development of the angle through the 4 quarters for 1 game", y = "Time", x = "Theta") +
  theme_bw()



```


```{r, fig.width=6, fig.height=4}

library(ggplot2)
library(reshape2)
library(grid)

set.seed(123)

require(ggplot2)


sg %>% 
  filter(wl_abbrv == "SEA (W)") %>%
  ggplot() + geom_histogram(aes(x = theta, fill = wl_abbrv),
                                 binwidth = 5) +
  scale_fill_manual(values = c("blue")) +
    scale_x_continuous(
        expand = c(0, 0),
        breaks = seq(180, 0, -30),
        limits = c(0, 360)
    ) +
    coord_polar(theta = "x",
                start = 3 * pi / 2,
                direction = -1) +
    theme_bw() +
    facet_wrap( ~ period_display_value, ncol = 2) +
    
    theme(
        panel.border = element_blank(),
        axis.title.y = element_text(hjust = 0.75, vjust = 3),
        legend.position = "top"
    )



# g = ggplotGrob(p)
# 
# grid.newpage()
# pushViewport(viewport(height = 1, width = 1, clip="on"))
# grid.draw(g)
# grid.rect(x = 0, y = -0.05, height = 1, width = 2, gp = gpar(col="white"))
# grid.rect(x = .5, y = .7, width = .6, height = .55, gp = gpar(lwd = 1, col = "black", fill = NA))

```



```{r}

library(circular)

data<- c(-0.188,-0.742,-0.953,-0.948,-0.953,-1.187,-0.9327200,-0.855,-  0.024,1.303,-1.041,-1.068,-1.066,1.442,1.150,0.965,0.665,0.649,0.984,-1.379,-0.584,-0.573,-0.357,-0.237,-0.287,-0.486,-0.783,-0.298,0.849,1.088,-1.003,-0.952,-0.776,-0.811,-0.880)

freq <- diff(colSums(outer( data %% (2*pi), (1:24)*pi/12,"<"))) / length(data)
r.max <- sqrt(max(freq))

#-----------------------------------------------------------------
# Plot the half circle:

lab.width  <- 0.15*r.max
lab.height <- 0.15*r.max

plot( c(-r.max,r.max), c(0,0),
      axes=FALSE,
      ylim=c(0,r.max+lab.height),
      xlim=c(-r.max-lab.width,r.max+lab.width),
      xlab="", ylab="", type="l")

for ( i in 0:(5*12-1) )
{
  psi <- i*pi/(5*12)
  x1 <- r.max*cos(psi)
  y1 <- r.max*sin(psi)
  x2 <- r.max*cos(psi+pi/(5*12))
  y2 <- r.max*sin(psi+pi/(5*12))

  lines( c(x1,x2), c(y1,y2), type="l")

  if (i %% 5 == 0) { lines( x1*c(1,0.95), y1*c(1,0.95), type="l" ) }
}

par(cex=2.0)

text( x = c(-r.max,0,r.max),
      y = c(0,r.max,0),
      labels = c("-pi/2","0","pi/2"),
      pos = c(2,3,4))

#------------------------------------------------------------
# Plot the distribution, but without the circle:

rose.diag(data,
          bins = 24,
          rotation = "clock",
          tcl.text = NA,
          ticks = FALSE,
          zero = pi/2,
          control.circle = circle.control( col="white" ),
          add = TRUE )


```



```{r}

library(gganimate)

g <- c_sea_games %>% 
  filter(period_number < 5 & wl_abbrv == "SEA (W)" & period_number == 1) %>% 
  ggplot(aes(x = distance)) +
  geom_histogram(aes(y = after_stat(density)), binwidth = 1) +
  labs(title = "distance for SEA over the 7 games they won {frame_along}")

g + transition_reveal(sequence_number, keep_last = TRUE)

```





## 

```{r}

sg %>%
  filter(period_number == 1 & distance <= 30) %>%
  ggplot(aes(x = distance, color = win_team_id)) +
  geom_histogram(size = 1, position = "dodge") +
  theme_bw()

sg %>%
  filter(period_number == 2 & distance <= 30) %>%
  ggplot(aes(x = distance, color = win_team_id)) +
  geom_freqpoly() +
  theme_bw()

```

# trying out the hidden markov model


```{r}

## quick test

winSG_G <-  sg %>% 
  filter(win_team_id == "win_team")

winSG <-  sg %>% 
  filter(win_team_id == "win_team") %>% 
  dplyr::select(sequence_number, distance)

winSG_G %>% 
  ggplot() + 
  geom_vline(xintercept = 600, , color = "blue", size=1.5, alpha = 0.3) + 
  geom_vline(xintercept = 600*2, , color = "blue", size=1.5, alpha = 0.3) + 
  geom_vline(xintercept = 600*3, , color = "blue", size=1.5, alpha = 0.3) + 
  geom_point(aes(x = time_corrected, y = distance, shape = win_team_id, size = scoring_play, color = win_team_id)) +
  scale_x_time() +
  labs(title = "Development of distance through the 4 quarters for 1 game", y = "Distance From Hoop", x = "Time") + 
  theme_bw()


HMM_distance_classify <- function(sg, team_wlabbrv) {
  focus_SG <- sg %>% 
    filter(wl_abbrv == team_wlabbrv) %>% 
    dplyr::select(team, distance)
  
}





library("depmixS4")
mod <- depmix(response = distance ~ 1, data = winSG, nstates = 3)
fm = fit(mod)

summary(fm)

```

```{r}
prstates = apply(posterior(fm)[,c("S1", "S2", "S3")], 1, which.max)

plot(prstates, type = "b", xlab = "Time", ylab = "State")

t_state = posterior(fm)["state"]

mu = summary(fm)[,1]
mu[2]


# viterbi(fm) == posterior(fm)

winSG_G$state = as.factor(prstates)

mu = summary(fm)[,1]
winSG_G$truMU = mu[prstates]

winSG_G %>% 
  ggplot() + 
  geom_vline(xintercept = 600, , color = "blue", size=1.5, alpha = 0.3) + 
  geom_vline(xintercept = 600*2, , color = "blue", size=1.5, alpha = 0.3) + 
  geom_vline(xintercept = 600*3, , color = "blue", size=1.5, alpha = 0.3) + 
  geom_point(aes(x = time_corrected, y = distance, shape = win_team_id, size = scoring_play, color = state)) +
  geom_line(aes(x = time_corrected, y = truMU)) +
  scale_x_time() +
  labs(title = "Hidden Markov Model Prediction of Distance changes over 4 quarters", y = "Distance From Hoop", x = "Time") + 
  theme_bw()

```


## trying out animations

```{r}

# https://goodekat.github.io/presentations/2019-isugg-gganimate-spooky/slides.html#48
library(glue)
name <- "Fred"
glue("{name}")

sg %>% 
  ggplot() + 
  geom_point(aes(x = coordinate_x, y = coordinate_y, color = wl_abbrv, group = sequence_number)) + # 
  labs(title = "test", subtitle =  "test: {frame_along}") +
  transition_reveal(along = sequence_number) 
  # shadow_wake(wake_length = 0.1, alpha = 0.5)
  # transition_states(time_corrected, transition_length = 1, state_length = 1)
  # transition_time(time = time_corrected)


sg %>% 
  ggplot() + 
  geom_point(aes(x = coordinate_x, y = coordinate_y, color = wl_abbrv)) +
  labs(title = "test", subtitle =  "test: {frame_along}") 
animate(anim, nframes = 200, fps = 2)

```






